AllCops:
  TargetRubyVersion: 2.7

# コメントは日本語で OK
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# 行の文字数を制限しない
Layout/LineLength:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

# クラスの長さを制限しない
Metrics/ClassLength:
  Enabled: false

# モジュールの長さを制限しない
Metrics/ModuleLength:
  Enabled: false

# メソッドの長さを制限しない
Metrics/MethodLength:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false
